### PR TITLE
Fix ctrl+k not working & being captured by browser

### LINKED ISSUE #8: Chrome on Windows already uses Ctrl + k
This may affect other browsers also but I've only tested with Chrome. Palette's keyboard shortcut is already used for a Chrome feature, so it's currently impossible to use your app. It's documented here: https://support.google.com/chrome/answer/157179?hl=en&co=GENIE.Platform%3DDesktop#zippy=%2Caddress-bar-shortcuts:~:text=Search%20from%20anywhere%20on%20the%20page

I'm not sure what the best solution to this is. I tried using preventDefault and stopPropagation but it didn't work for me. I found a discussion about this same key combo here: https://github.com/orgs/community/discussions/24057#discussion-4250265

### PR DESCRIPTION
**Pull request by EnriqueSoria**
With this changes it works for me both on Firefox and Chrome (on Ubuntu 20.04). Fixes #8

### CODE REVIEW

**Comment by rajasimon** [comment]
@jgillard can you confirm this works in your machine?

**Comment by EnriqueSoria** [comment]
> @jgillard can you confirm this works in your machine?

Also, can anyone confirm if it works on Mac?

**Comment by rajasimon** [comment]
@EnriqueSoria yeah I'm on Mac let me check quickly...

**Comment by rajasimon** [comment]
Confirmed! It's working for Mac ( Safari, Chrome, firefox )

**Comment by jgillard** [comment]
I've tested this with Chrome & Safari on Mac, Chrome & Edge on Windows (VM), and my team has tested it with 2 flavours of Linux, and everyone is happy.

**Comment by EnriqueSoria** [comment]
I'm impressed how fast have this gone... yesterday I didn't even know this package existed!

Thanks for reviewing this PR in such a small amount of time! :heart:

**Pull request merged**
